version: "1"
rules:                           # Array of rules
  - base: master                 # Required. Target branch
    upstream: jedisct1:master    # Required. Must be in the same fork network.
    autoMerge: false             # Optional, Default: false
    autoMergeHardReset: false    # Optional, Default: false DANGEROUS Wipes target branch changes and reset ref to match upstream
    assignees:                   # Optional
      - NullVoxPopuli
    reviewers:                   # Optional
      - NullVoxPopuli
label: ":arrow_heading_down: pull"       # Optional
