version: "1"
rules:
  - base: master
    upstream:  jedisct1:master
    autoMerge: true
    autoMergeHardReset: false
    reviewers:
      - NullVoxPopuli

# label: ":arrow_heading_down: pull"       # Optional
